### ISSUE TITLE
What is PitifulVM used for?

### ISSUE THREAD

**Issue by lazyparser** [sysprog21/pitifulvm#1]
Hi @jserv

glad to see your new work!

what is the PitifulVM used for? is it a simple but powerful prototype implementation for college course / classroom? if so, would I used it in my future courses?

**Comment by lazyparser** [comment]
for I am working on RISC-V recently, I'd like to try PitifulVM on Fedora/RISC-V[1] first ;-)

[1] https://github.com/isrc-cas/PLCT-Toolbox/blob/master/deploy_riscv64fedora_qemu.sh

**Comment by jserv** [comment]
`PitifulVM` was created for educational purpose. I look for some tiny projects as lecture assignments. Thus, I was working on [rv32emu](https://github.com/sysprog21/rv32emu) and this project. Being less than 700LoC, it should be a good start for students who learn system programming.

**Comment by lazyparser** [comment]
Thanks for open source  🎉
